// Emits JSON Schema for every v1alpha1 manifest kind into registry/schemas/.
// Run with: pnpm --filter @kernelindex/web schemas:generate
import { mkdirSync, writeFileSync } from "node:fs"
import path from "node:path"
import { z } from "zod"
import { manifestSchemas } from "../src/schemas/kinds.ts"

const outDir = path.resolve(import.meta.dirname, "../../../registry/schemas")
mkdirSync(outDir, { recursive: true })

const kebab = (kind: string) =>
  kind.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()

for (const [kind, schema] of Object.entries(manifestSchemas)) {
  const jsonSchema = z.toJSONSchema(schema, {
    io: "input",
    target: "draft-2020-12",
  })
  const file = `${kebab(kind)}.v1alpha1.schema.json`
  const document = {
    $comment:
      "Generated by apps/web/scripts/generate-schemas.ts — do not edit by hand.",
    $id: `https://kernelindex.com/schemas/v1alpha1/${kebab(kind)}.schema.json`,
    title: kind,
    ...jsonSchema,
  }
  writeFileSync(
    path.join(outDir, file),
    `${JSON.stringify(document, null, 2)}\n`,
  )
  console.log(`wrote registry/schemas/${file}`)
}
